const allRoles = {
  admin: [
    'GET_SUB_COMPANYS',
    'MANAGE_SUB_COMPANYS',
    'GET_SUPER_MASTERS',
    'MANAGE_SUPER_MASTERS',
    'GET_SUPER_STOCKISTS',
    'MANAGE_SUPER_STOCKISTS',
    'GET_STOCKISTS',
    'MANAGE_STOCKISTS',
    'GET_SUPER_AGENTS',
    'MANAGE_SUPER_AGENTS',
    'GET_AGENTS',
    'MANAGE_AGENTS',
    'GET_USERS',
    'MANAGE_USERS',
  ],
  subCompany: [
    'GET_SUPER_MASTERS',
    'MANAGE_SUPER_MASTERS',
    'GET_SUPER_STOCKISTS',
    'MANAGE_SUPER_STOCKISTS',
    'GET_STOCKISTS',
    'MANAGE_STOCKISTS',
    'GET_SUPER_AGENTS',
    'MANAGE_SUPER_AGENTS',
    'GET_AGENTS',
    'MANAGE_AGENTS',
    'GET_USERS',
    'MANAGE_USERS',
  ],
  superMaster: [
    'GET_SUPER_STOCKISTS',
    'MANAGE_SUPER_STOCKISTS',
    'GET_STOCKISTS',
    'MANAGE_STOCKISTS',
    'GET_SUPER_AGENTS',
    'MANAGE_SUPER_AGENTS',
    'GET_AGENTS',
    'MANAGE_AGENTS',
    'GET_USERS',
    'MANAGE_USERS',
  ],
  superStockist: [
    'GET_STOCKISTS',
    'MANAGE_STOCKISTS',
    'GET_SUPER_AGENTS',
    'MANAGE_SUPER_AGENTS',
    'GET_AGENTS',
    'MANAGE_AGENTS',
    'GET_USERS',
    'MANAGE_USERS',
  ],
  stockist: [
    'GET_SUPER_AGENTS',
    'MANAGE_SUPER_AGENTS',
    'GET_AGENTS',
    'MANAGE_AGENTS',
    'GET_USERS',
    'MANAGE_USERS',
  ],
  superAgent: [
    'GET_AGENTS',
    'MANAGE_AGENTS',
    'GET_USERS',
    'MANAGE_USERS',
  ],
  agent: [
    'GET_USERS',
    'MANAGE_USERS',
  ],
  user: [],
};

const roles = Object.keys(allRoles);
const roleRights = new Map(Object.entries(allRoles));

module.exports = {
  roles,
  roleRights,
};
